import { toCamelCase } from "drizzle-orm/casing";
import { Column, Table } from "./get-schema";
import { singularize } from "inflection";

function singularPascalCase(str: string) {
    const singular = singularize(str);
    const parts = singular.replace(/([a-z])([A-Z])/g, "$1_$2").replace(/[-\s]+/g, "_").toLowerCase().split(/_|-|\s+/);
    return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  }
  
  function pascalCase(str: string) {
    const c = toCamelCase(str);
    return c ? c.charAt(0).toUpperCase() + c.slice(1) : "";
  }
  
  // --- Zod rendering (Zod 4 mini style) ---
  function renderZodBaseType(zodType: string, isReadField: boolean, coerceDates = true) {
    switch (zodType) {
      case "string":
      case "email":
      case "url":
      case "uuid":
        return "z.string()";
      case "int":
      case "number":
        return "z.number()";
      case "boolean":
        return "z.boolean()";
      case "date":
        return coerceDates && isReadField ? "z.coerce.date()" : "z.date()";
      case "unknown":
        return "z.unknown()";
      default:
        return "z.unknown()";
    }
  }
  
  function renderReadField(col: Column, opts: { nullsToUndefined?: boolean, coerceDates?: boolean } = {}) {
    const { nullsToUndefined = true } = opts;
    let z = col.isEnum
      ? `z.enum(${col.enumConstantName})`
      : renderZodBaseType(col.zodType, true, opts.coerceDates ?? true);
  
    if (col.isArray) z = `z.array(${z})`;
    if (col.isNullable) z = `z.nullable(${z})`;
    if (col.isReadOptional) z = `z.optional(${z})`;
    if (
      (col.isNullable || col.isReadOptional) &&
      nullsToUndefined &&
      !col.isArray
    )
      z = `z.pipe(${z}, z.transform(val => val ?? undefined))`;
  
    return z;
  }
  
  function renderWriteField(col: Column, opts: { coerceDates?: boolean } = {}) {
    if (col.name === "id") {
      return "z.cuid2()";
    }
  
    let z = col.isEnum
      ? `z.enum(${col.enumConstantName})`
      : renderZodBaseType(col.zodType, false, opts.coerceDates ?? true);
  
    if (col.name === "email") {
      z = "z.email()";
    }
  
    const baseType = ["string", "email", "url", "uuid"].includes(col.zodType)
      ? "string"
      : ["int", "number"].includes(col.zodType)
      ? "number"
      : "other";
  
    if (baseType === "string" && !col.isEnum) {
      if (col.minLen != null) z += `.check(z.minLength(${col.minLen}))`;
      if (col.maxLen != null) z += `.check(z.maxLength(${col.maxLen}))`;
    }
    if (baseType === "number" && !col.isEnum) {
      if (col.minLen != null) z += `.check(z.minimum(${col.minLen}))`;
      if (col.maxLen != null) z += `.check(z.maximum(${col.maxLen}))`;
    }
  
    if (col.isNullable) z = `z.nullable(${z})`;
    if (col.isWriteOptional) z = `z.optional(${z})`;
  
    return z;
  }
  
  function formatTableSchemaName(tableName: string, op: "read" | "insert") {
    const base =
      pascalCase(tableName) + (op === "read" ? "Response" : "Request");
    return base + "Schema";
  }
  
  function formatEnumConstantName(tableName: string, colName: string) {
    const tablePart = tableName.replace(/-/g, "_").toUpperCase();
    const colPart = colName.replace(/-/g, "_").toUpperCase();
    return `${tablePart}_${colPart}`;
  }
  
  export function generateTableFile(table: Table) {
    const coerceDates = true;
    const nullsToUndefined = true;
    const minLenRequiredStrings = 1;
  
    for (const col of table.columns) {
      if (col.isEnum && col.enumValues?.length) {
        col.enumConstantName = formatEnumConstantName(table.name, col.name);
      }
      col.renderedReadType = renderReadField(col, {
        coerceDates,
        nullsToUndefined,
      });
    }
  
    const writableColumns = table.columns.filter((c) => c.isWritable);
    for (const col of writableColumns) {
      if (
        minLenRequiredStrings &&
        !col.isWriteOptional &&
        ["string", "email", "url", "uuid"].includes(col.zodType) &&
        !col.isEnum
      ) {
        col.minLen = col.minLen ?? 1;
      }
      col.renderedWriteType = renderWriteField(col, { coerceDates });
    }
  
    const enums = table.columns.filter((c) => c.isEnum && c.enumValues?.length);
    const enumBlocks = enums.map((c) => {
      const vals = c.enumValues?.map((v) => `'${v}'`).join(", ") ?? "";
      return `export const ${c.enumConstantName} = [${vals}] as const;`;
    });
  
    const readSchemaName = formatTableSchemaName(table.name, "read");
    const insertSchemaName = formatTableSchemaName(table.name, "insert");
  
    const singularPascalCaseName = singularPascalCase(table.name);
    const lowerCaseFirstLetterName = singularPascalCaseName.charAt(0).toLowerCase() + singularPascalCaseName.slice(1);
  
    let out = `// This file is auto-generated by 'npm run zod:generate'. Do not edit this file directly.
  import { z } from 'zod/mini';
  
  const ${lowerCaseFirstLetterName}IdSchema = z.cuid2().brand("${singularPascalCaseName}Id");
  
  export const ${singularPascalCaseName}Id = z.custom<${singularPascalCaseName}Id>((val) => {
      return ${lowerCaseFirstLetterName}IdSchema.safeParse(val).success;
  });
  
  export type ${singularPascalCaseName}Id = z.infer<typeof ${lowerCaseFirstLetterName}IdSchema>;
  
  ${enumBlocks.join("\n")}
  
  export const ${readSchemaName} = z.object({
  ${table.columns
    .map((c) => `    ${c.propertyName}: ${c.renderedReadType},`)
    .join("\n")}
  });
  `;
  
    if (writableColumns.length > 0) {
      out += `
  export const ${insertSchemaName} = z.object({
  ${writableColumns
    .map((c) => `    ${c.propertyName}: ${c.renderedWriteType},`)
    .join("\n")}
  });
  `;
    }
  
    return out;
  }
  