import { toCamelCase } from "drizzle-orm/casing";
import { singularize } from "inflection";
import type { Column, Table } from "./get-schema";

function singularPascalCase(str: string) {
	const singular = singularize(str);
	const parts = singular
		.replace(/([a-z])([A-Z])/g, "$1_$2")
		.replace(/[-\s]+/g, "_")
		.toLowerCase()
		.split(/_|-|\s+/);
	return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

function pascalCase(str: string) {
	const c = toCamelCase(str);
	return c ? c.charAt(0).toUpperCase() + c.slice(1) : "";
}

function renderValibotBaseType(
	baseType: string,
	isReadField: boolean,
	coerceDates = true,
) {
	switch (baseType) {
		case "string":
		case "email":
		case "url":
		case "uuid":
			return "v.string()";
		case "int":
		case "number":
			return "v.number()";
		case "boolean":
			return "v.boolean()";
		case "date":
			return coerceDates && isReadField
				? "v.pipe(v.unknown(), v.transform((input) => new Date(input as any)))"
				: "v.date()";
		case "unknown":
			return "v.unknown()";
		default:
			return "v.unknown()";
	}
}

function renderReadField(
	col: Column,
	opts: { nullsToUndefined?: boolean; coerceDates?: boolean } = {},
) {
	const { nullsToUndefined = true } = opts;
	let schema = col.isEnum
		? `v.picklist(${col.enumConstantName})`
		: renderValibotBaseType(col.baseType, true, opts.coerceDates ?? true);

	if (col.isArray) schema = `v.array(${schema})`;
	if (col.isNullable) schema = `v.nullable(${schema})`;
	if (col.isReadOptional) schema = `v.optional(${schema})`;
	if (
		(col.isNullable || col.isReadOptional) &&
		nullsToUndefined &&
		!col.isArray
	)
		schema = `v.pipe(${schema}, v.transform((val) => val ?? undefined))`;

	return schema;
}

function renderWriteField(col: Column, opts: { coerceDates?: boolean } = {}) {
	if (col.name === "id") {
		return "v.pipe(v.string(), v.cuid2())";
	}

	const isEmail = col.name === "email";
	const base = col.isEnum
		? `v.picklist(${col.enumConstantName})`
		: renderValibotBaseType(col.baseType, false, opts.coerceDates ?? true);

	const actions: string[] = [];

	if (isEmail && !col.isEnum) {
		actions.push("v.email()");
	}

	const baseTypeCategory = ["string", "email", "url", "uuid"].includes(
		col.baseType,
	)
		? "string"
		: ["int", "number"].includes(col.baseType)
			? "number"
			: "other";

	if (baseTypeCategory === "string" && !col.isEnum) {
		if (col.minLen != null) actions.push(`v.minLength(${col.minLen})`);
		if (col.maxLen != null) actions.push(`v.maxLength(${col.maxLen})`);
	}
	if (baseTypeCategory === "number" && !col.isEnum) {
		if (col.minLen != null) actions.push(`v.minValue(${col.minLen})`);
		if (col.maxLen != null) actions.push(`v.maxValue(${col.maxLen})`);
	}

	let schema =
		actions.length > 0 ? `v.pipe(${base}, ${actions.join(", ")})` : base;

	if (col.isNullable) schema = `v.nullable(${schema})`;
	if (col.isWriteOptional) schema = `v.optional(${schema})`;

	return schema;
}

function formatTableSchemaName(tableName: string, op: "read" | "insert") {
	const base = pascalCase(tableName) + (op === "read" ? "Response" : "Request");
	return `${base}Schema`;
}

function formatEnumConstantName(tableName: string, colName: string) {
	const tablePart = tableName.replace(/-/g, "_").toUpperCase();
	const colPart = colName.replace(/-/g, "_").toUpperCase();
	return `${tablePart}_${colPart}`;
}

export function generateTableFile(table: Table) {
	const coerceDates = true;
	const nullsToUndefined = true;
	const minLenRequiredStrings = 1;

	for (const col of table.columns) {
		if (col.isEnum && col.enumValues?.length) {
			col.enumConstantName = formatEnumConstantName(table.name, col.name);
		}
		col.renderedReadType = renderReadField(col, {
			coerceDates,
			nullsToUndefined,
		});
	}

	const writableColumns = table.columns.filter((c) => c.isWritable);
	for (const col of writableColumns) {
		if (
			minLenRequiredStrings &&
			!col.isWriteOptional &&
			["string", "email", "url", "uuid"].includes(col.baseType) &&
			!col.isEnum
		) {
			col.minLen = col.minLen ?? 1;
		}
		col.renderedWriteType = renderWriteField(col, { coerceDates });
	}

	const enums = table.columns.filter((c) => c.isEnum && c.enumValues?.length);
	const enumBlocks = enums.map((c) => {
		const vals = c.enumValues?.map((v) => `'${v}'`).join(", ") ?? "";
		return `export const ${c.enumConstantName} = [${vals}] as const;`;
	});

	const readSchemaName = formatTableSchemaName(table.name, "read");
	const insertSchemaName = formatTableSchemaName(table.name, "insert");

	const singularPascalCaseName = singularPascalCase(table.name);

	let out = `// This file is auto-generated by 'npm run valibot:generate'. Do not edit this file directly.
	 /** biome-ignore-all lint/suspicious/noExplicitAny: auto-generated code */
  import * as v from 'valibot';
  
  const ${singularPascalCaseName}IdSchema = v.pipe(v.string(), v.cuid2(), v.brand("${singularPascalCaseName}Id"));
  
  export const ${singularPascalCaseName}Id: ${singularPascalCaseName}Id = v.parse(${singularPascalCaseName}IdSchema, "123");
  
  export type ${singularPascalCaseName}Id = v.InferOutput<typeof ${singularPascalCaseName}IdSchema>;
  
  ${enumBlocks.join("\n")}
  
  export const ${readSchemaName} = v.object({
  ${table.columns
		.map((c) => `    ${c.propertyName}: ${c.renderedReadType},`)
		.join("\n")}
  });
  `;

	if (writableColumns.length > 0) {
		out += `
  export const ${insertSchemaName} = v.object({
  ${writableColumns
		.map((c) => `    ${c.propertyName}: ${c.renderedWriteType},`)
		.join("\n")}
  });
  `;
	}

	return out;
}
