// This file is auto-generated by 'npm run valibot:generate'. Do not edit this file directly.
/** biome-ignore-all lint/suspicious/noExplicitAny: auto-generated code */
import * as v from "valibot";

const AuthSessionIdSchema = v.pipe(
	v.string(),
	v.cuid2(),
	v.brand("AuthSessionId"),
);

export const AuthSessionId: AuthSessionId = v.parse(AuthSessionIdSchema, "123");

export type AuthSessionId = v.InferOutput<typeof AuthSessionIdSchema>;

export const AuthSessionsResponseSchema = v.object({
	id: v.string(),
	lastVerifiedAt: v.pipe(
		v.unknown(),
		v.transform((input) => new Date(input as any)),
	),
	secretHash: v.string(),
	userId: v.string(),
	sessionId: v.string(),
	deletedAt: v.pipe(
		v.optional(
			v.nullable(
				v.pipe(
					v.unknown(),
					v.transform((input) => new Date(input as any)),
				),
			),
		),
		v.transform((val) => val ?? undefined),
	),
	createdAt: v.pipe(
		v.unknown(),
		v.transform((input) => new Date(input as any)),
	),
	updatedAt: v.pipe(
		v.unknown(),
		v.transform((input) => new Date(input as any)),
	),
});

export const AuthSessionsRequestSchema = v.object({
	id: v.pipe(v.string(), v.cuid2()),
	lastVerifiedAt: v.date(),
	secretHash: v.pipe(v.string(), v.minLength(1), v.maxLength(128)),
	userId: v.pipe(v.string(), v.minLength(1), v.maxLength(24)),
	sessionId: v.pipe(v.string(), v.minLength(1), v.maxLength(128)),
	deletedAt: v.optional(v.nullable(v.date())),
	createdAt: v.optional(v.date()),
	updatedAt: v.optional(v.date()),
});
