/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as StoreTermsOfServiceRouteImport } from './routes/store-terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MarketplaceGuidelinesRouteImport } from './routes/marketplace-guidelines'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as formsRouteRouteImport } from './routes/(forms)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as formsCreateStoreRouteImport } from './routes/(forms)/create-store'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotpasswordRouteImport } from './routes/(auth)/forgotpassword'
import { Route as appStoresRouteImport } from './routes/(app)/stores'
import { Route as appSearchRouteImport } from './routes/(app)/search'
import { Route as appHelpRouteImport } from './routes/(app)/help'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appCartRouteImport } from './routes/(app)/cart'
import { Route as appChatRouteRouteImport } from './routes/(app)/chat/route'
import { Route as appSellerIndexRouteImport } from './routes/(app)/seller/index'
import { Route as appChatIndexRouteImport } from './routes/(app)/chat/index'
import { Route as appStoreStoreSlugRouteImport } from './routes/(app)/store.$storeSlug'
import { Route as appProductProductSlugRouteImport } from './routes/(app)/product.$productSlug'
import { Route as appChatStoreSlugRouteImport } from './routes/(app)/chat/$storeSlug'
import { Route as appCategoryCategorySlugRouteImport } from './routes/(app)/category.$categorySlug'
import { Route as appaccountAccountRouteImport } from './routes/(app)/(account)/account'
import { Route as appSellerStoreIdSettingsRouteImport } from './routes/(app)/seller/$storeId/settings'
import { Route as appSellerStoreIdProductsRouteImport } from './routes/(app)/seller/$storeId/products'
import { Route as appSellerStoreIdProductNewRouteImport } from './routes/(app)/seller/$storeId/product-new'
import { Route as appSellerStoreIdOrdersRouteImport } from './routes/(app)/seller/$storeId/orders'
import { Route as appSellerStoreIdDashboardRouteImport } from './routes/(app)/seller/$storeId/dashboard'
import { Route as appSellerStoreIdAnalyticsRouteImport } from './routes/(app)/seller/$storeId/analytics'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTermsOfServiceRoute = StoreTermsOfServiceRouteImport.update({
  id: '/store-terms-of-service',
  path: '/store-terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceGuidelinesRoute = MarketplaceGuidelinesRouteImport.update({
  id: '/marketplace-guidelines',
  path: '/marketplace-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const formsRouteRoute = formsRouteRouteImport.update({
  id: '/(forms)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const formsCreateStoreRoute = formsCreateStoreRouteImport.update({
  id: '/create-store',
  path: '/create-store',
  getParentRoute: () => formsRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotpasswordRoute = authForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => authRouteRoute,
} as any)
const appStoresRoute = appStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => appRouteRoute,
} as any)
const appSearchRoute = appSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => appRouteRoute,
} as any)
const appHelpRoute = appHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appCartRoute = appCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatRouteRoute = appChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appRouteRoute,
} as any)
const appSellerIndexRoute = appSellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appChatRouteRoute,
} as any)
const appStoreStoreSlugRoute = appStoreStoreSlugRouteImport.update({
  id: '/store/$storeSlug',
  path: '/store/$storeSlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductProductSlugRoute = appProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatStoreSlugRoute = appChatStoreSlugRouteImport.update({
  id: '/$storeSlug',
  path: '/$storeSlug',
  getParentRoute: () => appChatRouteRoute,
} as any)
const appCategoryCategorySlugRoute = appCategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appaccountAccountRoute = appaccountAccountRouteImport.update({
  id: '/(account)/account',
  path: '/account',
  getParentRoute: () => appRouteRoute,
} as any)
const appSellerStoreIdSettingsRoute =
  appSellerStoreIdSettingsRouteImport.update({
    id: '/seller/$storeId/settings',
    path: '/seller/$storeId/settings',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSellerStoreIdProductsRoute =
  appSellerStoreIdProductsRouteImport.update({
    id: '/seller/$storeId/products',
    path: '/seller/$storeId/products',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSellerStoreIdProductNewRoute =
  appSellerStoreIdProductNewRouteImport.update({
    id: '/seller/$storeId/product-new',
    path: '/seller/$storeId/product-new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSellerStoreIdOrdersRoute = appSellerStoreIdOrdersRouteImport.update({
  id: '/seller/$storeId/orders',
  path: '/seller/$storeId/orders',
  getParentRoute: () => appRouteRoute,
} as any)
const appSellerStoreIdDashboardRoute =
  appSellerStoreIdDashboardRouteImport.update({
    id: '/seller/$storeId/dashboard',
    path: '/seller/$storeId/dashboard',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSellerStoreIdAnalyticsRoute =
  appSellerStoreIdAnalyticsRouteImport.update({
    id: '/seller/$storeId/analytics',
    path: '/seller/$storeId/analytics',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/chat': typeof appChatRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/categories': typeof appCategoriesRoute
  '/help': typeof appHelpRoute
  '/search': typeof appSearchRoute
  '/stores': typeof appStoresRoute
  '/forgotpassword': typeof authForgotpasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-store': typeof formsCreateStoreRoute
  '/': typeof appIndexRoute
  '/account': typeof appaccountAccountRoute
  '/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/product/$productSlug': typeof appProductProductSlugRoute
  '/store/$storeSlug': typeof appStoreStoreSlugRoute
  '/chat/': typeof appChatIndexRoute
  '/seller/': typeof appSellerIndexRoute
  '/seller/$storeId/analytics': typeof appSellerStoreIdAnalyticsRoute
  '/seller/$storeId/dashboard': typeof appSellerStoreIdDashboardRoute
  '/seller/$storeId/orders': typeof appSellerStoreIdOrdersRoute
  '/seller/$storeId/product-new': typeof appSellerStoreIdProductNewRoute
  '/seller/$storeId/products': typeof appSellerStoreIdProductsRoute
  '/seller/$storeId/settings': typeof appSellerStoreIdSettingsRoute
}
export interface FileRoutesByTo {
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/cart': typeof appCartRoute
  '/categories': typeof appCategoriesRoute
  '/help': typeof appHelpRoute
  '/search': typeof appSearchRoute
  '/stores': typeof appStoresRoute
  '/forgotpassword': typeof authForgotpasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-store': typeof formsCreateStoreRoute
  '/': typeof appIndexRoute
  '/account': typeof appaccountAccountRoute
  '/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/product/$productSlug': typeof appProductProductSlugRoute
  '/store/$storeSlug': typeof appStoreStoreSlugRoute
  '/chat': typeof appChatIndexRoute
  '/seller': typeof appSellerIndexRoute
  '/seller/$storeId/analytics': typeof appSellerStoreIdAnalyticsRoute
  '/seller/$storeId/dashboard': typeof appSellerStoreIdDashboardRoute
  '/seller/$storeId/orders': typeof appSellerStoreIdOrdersRoute
  '/seller/$storeId/product-new': typeof appSellerStoreIdProductNewRoute
  '/seller/$storeId/products': typeof appSellerStoreIdProductsRoute
  '/seller/$storeId/settings': typeof appSellerStoreIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(forms)': typeof formsRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/(app)/chat': typeof appChatRouteRouteWithChildren
  '/(app)/cart': typeof appCartRoute
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/help': typeof appHelpRoute
  '/(app)/search': typeof appSearchRoute
  '/(app)/stores': typeof appStoresRoute
  '/(auth)/forgotpassword': typeof authForgotpasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(forms)/create-store': typeof formsCreateStoreRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/(account)/account': typeof appaccountAccountRoute
  '/(app)/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/(app)/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/(app)/product/$productSlug': typeof appProductProductSlugRoute
  '/(app)/store/$storeSlug': typeof appStoreStoreSlugRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/seller/': typeof appSellerIndexRoute
  '/(app)/seller/$storeId/analytics': typeof appSellerStoreIdAnalyticsRoute
  '/(app)/seller/$storeId/dashboard': typeof appSellerStoreIdDashboardRoute
  '/(app)/seller/$storeId/orders': typeof appSellerStoreIdOrdersRoute
  '/(app)/seller/$storeId/product-new': typeof appSellerStoreIdProductNewRoute
  '/(app)/seller/$storeId/products': typeof appSellerStoreIdProductsRoute
  '/(app)/seller/$storeId/settings': typeof appSellerStoreIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/chat'
    | '/cart'
    | '/categories'
    | '/help'
    | '/search'
    | '/stores'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/create-store'
    | '/'
    | '/account'
    | '/category/$categorySlug'
    | '/chat/$storeSlug'
    | '/product/$productSlug'
    | '/store/$storeSlug'
    | '/chat/'
    | '/seller/'
    | '/seller/$storeId/analytics'
    | '/seller/$storeId/dashboard'
    | '/seller/$storeId/orders'
    | '/seller/$storeId/product-new'
    | '/seller/$storeId/products'
    | '/seller/$storeId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/cart'
    | '/categories'
    | '/help'
    | '/search'
    | '/stores'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/create-store'
    | '/'
    | '/account'
    | '/category/$categorySlug'
    | '/chat/$storeSlug'
    | '/product/$productSlug'
    | '/store/$storeSlug'
    | '/chat'
    | '/seller'
    | '/seller/$storeId/analytics'
    | '/seller/$storeId/dashboard'
    | '/seller/$storeId/orders'
    | '/seller/$storeId/product-new'
    | '/seller/$storeId/products'
    | '/seller/$storeId/settings'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(forms)'
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/(app)/chat'
    | '/(app)/cart'
    | '/(app)/categories'
    | '/(app)/help'
    | '/(app)/search'
    | '/(app)/stores'
    | '/(auth)/forgotpassword'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(forms)/create-store'
    | '/(app)/'
    | '/(app)/(account)/account'
    | '/(app)/category/$categorySlug'
    | '/(app)/chat/$storeSlug'
    | '/(app)/product/$productSlug'
    | '/(app)/store/$storeSlug'
    | '/(app)/chat/'
    | '/(app)/seller/'
    | '/(app)/seller/$storeId/analytics'
    | '/(app)/seller/$storeId/dashboard'
    | '/(app)/seller/$storeId/orders'
    | '/(app)/seller/$storeId/product-new'
    | '/(app)/seller/$storeId/products'
    | '/(app)/seller/$storeId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  formsRouteRoute: typeof formsRouteRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  MarketplaceGuidelinesRoute: typeof MarketplaceGuidelinesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StoreTermsOfServiceRoute: typeof StoreTermsOfServiceRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-terms-of-service': {
      id: '/store-terms-of-service'
      path: '/store-terms-of-service'
      fullPath: '/store-terms-of-service'
      preLoaderRoute: typeof StoreTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-guidelines': {
      id: '/marketplace-guidelines'
      path: '/marketplace-guidelines'
      fullPath: '/marketplace-guidelines'
      preLoaderRoute: typeof MarketplaceGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(forms)': {
      id: '/(forms)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof formsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(forms)/create-store': {
      id: '/(forms)/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof formsCreateStoreRouteImport
      parentRoute: typeof formsRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgotpassword': {
      id: '/(auth)/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof authForgotpasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/stores': {
      id: '/(app)/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof appStoresRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/search': {
      id: '/(app)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof appSearchRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/help': {
      id: '/(app)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof appHelpRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cart': {
      id: '/(app)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof appCartRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat': {
      id: '/(app)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/': {
      id: '/(app)/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof appSellerIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appChatRouteRoute
    }
    '/(app)/store/$storeSlug': {
      id: '/(app)/store/$storeSlug'
      path: '/store/$storeSlug'
      fullPath: '/store/$storeSlug'
      preLoaderRoute: typeof appStoreStoreSlugRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/product/$productSlug': {
      id: '/(app)/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof appProductProductSlugRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/$storeSlug': {
      id: '/(app)/chat/$storeSlug'
      path: '/$storeSlug'
      fullPath: '/chat/$storeSlug'
      preLoaderRoute: typeof appChatStoreSlugRouteImport
      parentRoute: typeof appChatRouteRoute
    }
    '/(app)/category/$categorySlug': {
      id: '/(app)/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof appCategoryCategorySlugRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(account)/account': {
      id: '/(app)/(account)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appaccountAccountRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/settings': {
      id: '/(app)/seller/$storeId/settings'
      path: '/seller/$storeId/settings'
      fullPath: '/seller/$storeId/settings'
      preLoaderRoute: typeof appSellerStoreIdSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/products': {
      id: '/(app)/seller/$storeId/products'
      path: '/seller/$storeId/products'
      fullPath: '/seller/$storeId/products'
      preLoaderRoute: typeof appSellerStoreIdProductsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/product-new': {
      id: '/(app)/seller/$storeId/product-new'
      path: '/seller/$storeId/product-new'
      fullPath: '/seller/$storeId/product-new'
      preLoaderRoute: typeof appSellerStoreIdProductNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/orders': {
      id: '/(app)/seller/$storeId/orders'
      path: '/seller/$storeId/orders'
      fullPath: '/seller/$storeId/orders'
      preLoaderRoute: typeof appSellerStoreIdOrdersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/dashboard': {
      id: '/(app)/seller/$storeId/dashboard'
      path: '/seller/$storeId/dashboard'
      fullPath: '/seller/$storeId/dashboard'
      preLoaderRoute: typeof appSellerStoreIdDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/seller/$storeId/analytics': {
      id: '/(app)/seller/$storeId/analytics'
      path: '/seller/$storeId/analytics'
      fullPath: '/seller/$storeId/analytics'
      preLoaderRoute: typeof appSellerStoreIdAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appChatRouteRouteChildren {
  appChatStoreSlugRoute: typeof appChatStoreSlugRoute
  appChatIndexRoute: typeof appChatIndexRoute
}

const appChatRouteRouteChildren: appChatRouteRouteChildren = {
  appChatStoreSlugRoute: appChatStoreSlugRoute,
  appChatIndexRoute: appChatIndexRoute,
}

const appChatRouteRouteWithChildren = appChatRouteRoute._addFileChildren(
  appChatRouteRouteChildren,
)

interface appRouteRouteChildren {
  appChatRouteRoute: typeof appChatRouteRouteWithChildren
  appCartRoute: typeof appCartRoute
  appCategoriesRoute: typeof appCategoriesRoute
  appHelpRoute: typeof appHelpRoute
  appSearchRoute: typeof appSearchRoute
  appStoresRoute: typeof appStoresRoute
  appIndexRoute: typeof appIndexRoute
  appaccountAccountRoute: typeof appaccountAccountRoute
  appCategoryCategorySlugRoute: typeof appCategoryCategorySlugRoute
  appProductProductSlugRoute: typeof appProductProductSlugRoute
  appStoreStoreSlugRoute: typeof appStoreStoreSlugRoute
  appSellerIndexRoute: typeof appSellerIndexRoute
  appSellerStoreIdAnalyticsRoute: typeof appSellerStoreIdAnalyticsRoute
  appSellerStoreIdDashboardRoute: typeof appSellerStoreIdDashboardRoute
  appSellerStoreIdOrdersRoute: typeof appSellerStoreIdOrdersRoute
  appSellerStoreIdProductNewRoute: typeof appSellerStoreIdProductNewRoute
  appSellerStoreIdProductsRoute: typeof appSellerStoreIdProductsRoute
  appSellerStoreIdSettingsRoute: typeof appSellerStoreIdSettingsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChatRouteRoute: appChatRouteRouteWithChildren,
  appCartRoute: appCartRoute,
  appCategoriesRoute: appCategoriesRoute,
  appHelpRoute: appHelpRoute,
  appSearchRoute: appSearchRoute,
  appStoresRoute: appStoresRoute,
  appIndexRoute: appIndexRoute,
  appaccountAccountRoute: appaccountAccountRoute,
  appCategoryCategorySlugRoute: appCategoryCategorySlugRoute,
  appProductProductSlugRoute: appProductProductSlugRoute,
  appStoreStoreSlugRoute: appStoreStoreSlugRoute,
  appSellerIndexRoute: appSellerIndexRoute,
  appSellerStoreIdAnalyticsRoute: appSellerStoreIdAnalyticsRoute,
  appSellerStoreIdDashboardRoute: appSellerStoreIdDashboardRoute,
  appSellerStoreIdOrdersRoute: appSellerStoreIdOrdersRoute,
  appSellerStoreIdProductNewRoute: appSellerStoreIdProductNewRoute,
  appSellerStoreIdProductsRoute: appSellerStoreIdProductsRoute,
  appSellerStoreIdSettingsRoute: appSellerStoreIdSettingsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotpasswordRoute: typeof authForgotpasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotpasswordRoute: authForgotpasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface formsRouteRouteChildren {
  formsCreateStoreRoute: typeof formsCreateStoreRoute
}

const formsRouteRouteChildren: formsRouteRouteChildren = {
  formsCreateStoreRoute: formsCreateStoreRoute,
}

const formsRouteRouteWithChildren = formsRouteRoute._addFileChildren(
  formsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  formsRouteRoute: formsRouteRouteWithChildren,
  DeferredRoute: DeferredRoute,
  MarketplaceGuidelinesRoute: MarketplaceGuidelinesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StoreTermsOfServiceRoute: StoreTermsOfServiceRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
