/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as StoreTermsOfServiceRouteImport } from './routes/store-terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MarketplaceGuidelinesRouteImport } from './routes/marketplace-guidelines'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as formsRouteRouteImport } from './routes/(forms)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountReviewsRouteImport } from './routes/account/reviews'
import { Route as AccountPaymentsRouteImport } from './routes/account/payments'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountFollowingRouteImport } from './routes/account/following'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as formsCreateStoreRouteImport } from './routes/(forms)/create-store'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotpasswordRouteImport } from './routes/(auth)/forgotpassword'
import { Route as appStoresRouteImport } from './routes/(app)/stores'
import { Route as appSearchRouteImport } from './routes/(app)/search'
import { Route as appHelpRouteImport } from './routes/(app)/help'
import { Route as appCategoriesRouteImport } from './routes/(app)/categories'
import { Route as appCartRouteImport } from './routes/(app)/cart'
import { Route as MerchantStoreIdRouteRouteImport } from './routes/merchant/$storeId/route'
import { Route as appChatRouteRouteImport } from './routes/(app)/chat/route'
import { Route as MerchantStoreIdIndexRouteImport } from './routes/merchant/$storeId/index'
import { Route as appChatIndexRouteImport } from './routes/(app)/chat/index'
import { Route as MerchantStoreIdSettingsRouteImport } from './routes/merchant/$storeId/settings'
import { Route as MerchantStoreIdReviewsRouteImport } from './routes/merchant/$storeId/reviews'
import { Route as MerchantStoreIdPromotionsRouteImport } from './routes/merchant/$storeId/promotions'
import { Route as MerchantStoreIdProductsRouteImport } from './routes/merchant/$storeId/products'
import { Route as MerchantStoreIdProductNewRouteImport } from './routes/merchant/$storeId/product-new'
import { Route as MerchantStoreIdPayoutsRouteImport } from './routes/merchant/$storeId/payouts'
import { Route as MerchantStoreIdOrdersRouteImport } from './routes/merchant/$storeId/orders'
import { Route as MerchantStoreIdMessagesRouteImport } from './routes/merchant/$storeId/messages'
import { Route as MerchantStoreIdAnalyticsRouteImport } from './routes/merchant/$storeId/analytics'
import { Route as appProductProductSlugRouteImport } from './routes/(app)/product.$productSlug'
import { Route as appChatStoreSlugRouteImport } from './routes/(app)/chat/$storeSlug'
import { Route as appCategoryCategorySlugRouteImport } from './routes/(app)/category.$categorySlug'
import { Route as appStoreStoreSlugRouteRouteImport } from './routes/(app)/store/$storeSlug/route'
import { Route as appStoreStoreSlugIndexRouteImport } from './routes/(app)/store/$storeSlug/index'
import { Route as appStoreStoreSlugReviewsRouteImport } from './routes/(app)/store/$storeSlug/reviews'
import { Route as appStoreStoreSlugPoliciesRouteImport } from './routes/(app)/store/$storeSlug/policies'
import { Route as appStoreStoreSlugAboutRouteImport } from './routes/(app)/store/$storeSlug/about'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreTermsOfServiceRoute = StoreTermsOfServiceRouteImport.update({
  id: '/store-terms-of-service',
  path: '/store-terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceGuidelinesRoute = MarketplaceGuidelinesRouteImport.update({
  id: '/marketplace-guidelines',
  path: '/marketplace-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const formsRouteRoute = formsRouteRouteImport.update({
  id: '/(forms)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountFollowingRoute = AccountFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRouteRoute,
} as any)
const formsCreateStoreRoute = formsCreateStoreRouteImport.update({
  id: '/create-store',
  path: '/create-store',
  getParentRoute: () => formsRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotpasswordRoute = authForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => authRouteRoute,
} as any)
const appStoresRoute = appStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => appRouteRoute,
} as any)
const appSearchRoute = appSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => appRouteRoute,
} as any)
const appHelpRoute = appHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => appRouteRoute,
} as any)
const appCategoriesRoute = appCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => appRouteRoute,
} as any)
const appCartRoute = appCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => appRouteRoute,
} as any)
const MerchantStoreIdRouteRoute = MerchantStoreIdRouteRouteImport.update({
  id: '/merchant/$storeId',
  path: '/merchant/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatRouteRoute = appChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appRouteRoute,
} as any)
const MerchantStoreIdIndexRoute = MerchantStoreIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appChatRouteRoute,
} as any)
const MerchantStoreIdSettingsRoute = MerchantStoreIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdReviewsRoute = MerchantStoreIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdPromotionsRoute =
  MerchantStoreIdPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => MerchantStoreIdRouteRoute,
  } as any)
const MerchantStoreIdProductsRoute = MerchantStoreIdProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdProductNewRoute =
  MerchantStoreIdProductNewRouteImport.update({
    id: '/product-new',
    path: '/product-new',
    getParentRoute: () => MerchantStoreIdRouteRoute,
  } as any)
const MerchantStoreIdPayoutsRoute = MerchantStoreIdPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdOrdersRoute = MerchantStoreIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdMessagesRoute = MerchantStoreIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MerchantStoreIdRouteRoute,
} as any)
const MerchantStoreIdAnalyticsRoute =
  MerchantStoreIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => MerchantStoreIdRouteRoute,
  } as any)
const appProductProductSlugRoute = appProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatStoreSlugRoute = appChatStoreSlugRouteImport.update({
  id: '/$storeSlug',
  path: '/$storeSlug',
  getParentRoute: () => appChatRouteRoute,
} as any)
const appCategoryCategorySlugRoute = appCategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appStoreStoreSlugRouteRoute = appStoreStoreSlugRouteRouteImport.update({
  id: '/store/$storeSlug',
  path: '/store/$storeSlug',
  getParentRoute: () => appRouteRoute,
} as any)
const appStoreStoreSlugIndexRoute = appStoreStoreSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appStoreStoreSlugRouteRoute,
} as any)
const appStoreStoreSlugReviewsRoute =
  appStoreStoreSlugReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => appStoreStoreSlugRouteRoute,
  } as any)
const appStoreStoreSlugPoliciesRoute =
  appStoreStoreSlugPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => appStoreStoreSlugRouteRoute,
  } as any)
const appStoreStoreSlugAboutRoute = appStoreStoreSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appStoreStoreSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof AccountRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/chat': typeof appChatRouteRouteWithChildren
  '/merchant/$storeId': typeof MerchantStoreIdRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/categories': typeof appCategoriesRoute
  '/help': typeof appHelpRoute
  '/search': typeof appSearchRoute
  '/stores': typeof appStoresRoute
  '/forgotpassword': typeof authForgotpasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-store': typeof formsCreateStoreRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/': typeof appIndexRoute
  '/account/': typeof AccountIndexRoute
  '/store/$storeSlug': typeof appStoreStoreSlugRouteRouteWithChildren
  '/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/product/$productSlug': typeof appProductProductSlugRoute
  '/merchant/$storeId/analytics': typeof MerchantStoreIdAnalyticsRoute
  '/merchant/$storeId/messages': typeof MerchantStoreIdMessagesRoute
  '/merchant/$storeId/orders': typeof MerchantStoreIdOrdersRoute
  '/merchant/$storeId/payouts': typeof MerchantStoreIdPayoutsRoute
  '/merchant/$storeId/product-new': typeof MerchantStoreIdProductNewRoute
  '/merchant/$storeId/products': typeof MerchantStoreIdProductsRoute
  '/merchant/$storeId/promotions': typeof MerchantStoreIdPromotionsRoute
  '/merchant/$storeId/reviews': typeof MerchantStoreIdReviewsRoute
  '/merchant/$storeId/settings': typeof MerchantStoreIdSettingsRoute
  '/chat/': typeof appChatIndexRoute
  '/merchant/$storeId/': typeof MerchantStoreIdIndexRoute
  '/store/$storeSlug/about': typeof appStoreStoreSlugAboutRoute
  '/store/$storeSlug/policies': typeof appStoreStoreSlugPoliciesRoute
  '/store/$storeSlug/reviews': typeof appStoreStoreSlugReviewsRoute
  '/store/$storeSlug/': typeof appStoreStoreSlugIndexRoute
}
export interface FileRoutesByTo {
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/cart': typeof appCartRoute
  '/categories': typeof appCategoriesRoute
  '/help': typeof appHelpRoute
  '/search': typeof appSearchRoute
  '/stores': typeof appStoresRoute
  '/forgotpassword': typeof authForgotpasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-store': typeof formsCreateStoreRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/': typeof appIndexRoute
  '/account': typeof AccountIndexRoute
  '/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/product/$productSlug': typeof appProductProductSlugRoute
  '/merchant/$storeId/analytics': typeof MerchantStoreIdAnalyticsRoute
  '/merchant/$storeId/messages': typeof MerchantStoreIdMessagesRoute
  '/merchant/$storeId/orders': typeof MerchantStoreIdOrdersRoute
  '/merchant/$storeId/payouts': typeof MerchantStoreIdPayoutsRoute
  '/merchant/$storeId/product-new': typeof MerchantStoreIdProductNewRoute
  '/merchant/$storeId/products': typeof MerchantStoreIdProductsRoute
  '/merchant/$storeId/promotions': typeof MerchantStoreIdPromotionsRoute
  '/merchant/$storeId/reviews': typeof MerchantStoreIdReviewsRoute
  '/merchant/$storeId/settings': typeof MerchantStoreIdSettingsRoute
  '/chat': typeof appChatIndexRoute
  '/merchant/$storeId': typeof MerchantStoreIdIndexRoute
  '/store/$storeSlug/about': typeof appStoreStoreSlugAboutRoute
  '/store/$storeSlug/policies': typeof appStoreStoreSlugPoliciesRoute
  '/store/$storeSlug/reviews': typeof appStoreStoreSlugReviewsRoute
  '/store/$storeSlug': typeof appStoreStoreSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(forms)': typeof formsRouteRouteWithChildren
  '/account': typeof AccountRouteRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/marketplace-guidelines': typeof MarketplaceGuidelinesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/store-terms-of-service': typeof StoreTermsOfServiceRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/(app)/chat': typeof appChatRouteRouteWithChildren
  '/merchant/$storeId': typeof MerchantStoreIdRouteRouteWithChildren
  '/(app)/cart': typeof appCartRoute
  '/(app)/categories': typeof appCategoriesRoute
  '/(app)/help': typeof appHelpRoute
  '/(app)/search': typeof appSearchRoute
  '/(app)/stores': typeof appStoresRoute
  '/(auth)/forgotpassword': typeof authForgotpasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(forms)/create-store': typeof formsCreateStoreRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/following': typeof AccountFollowingRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/(app)/': typeof appIndexRoute
  '/account/': typeof AccountIndexRoute
  '/(app)/store/$storeSlug': typeof appStoreStoreSlugRouteRouteWithChildren
  '/(app)/category/$categorySlug': typeof appCategoryCategorySlugRoute
  '/(app)/chat/$storeSlug': typeof appChatStoreSlugRoute
  '/(app)/product/$productSlug': typeof appProductProductSlugRoute
  '/merchant/$storeId/analytics': typeof MerchantStoreIdAnalyticsRoute
  '/merchant/$storeId/messages': typeof MerchantStoreIdMessagesRoute
  '/merchant/$storeId/orders': typeof MerchantStoreIdOrdersRoute
  '/merchant/$storeId/payouts': typeof MerchantStoreIdPayoutsRoute
  '/merchant/$storeId/product-new': typeof MerchantStoreIdProductNewRoute
  '/merchant/$storeId/products': typeof MerchantStoreIdProductsRoute
  '/merchant/$storeId/promotions': typeof MerchantStoreIdPromotionsRoute
  '/merchant/$storeId/reviews': typeof MerchantStoreIdReviewsRoute
  '/merchant/$storeId/settings': typeof MerchantStoreIdSettingsRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/merchant/$storeId/': typeof MerchantStoreIdIndexRoute
  '/(app)/store/$storeSlug/about': typeof appStoreStoreSlugAboutRoute
  '/(app)/store/$storeSlug/policies': typeof appStoreStoreSlugPoliciesRoute
  '/(app)/store/$storeSlug/reviews': typeof appStoreStoreSlugReviewsRoute
  '/(app)/store/$storeSlug/': typeof appStoreStoreSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/chat'
    | '/merchant/$storeId'
    | '/cart'
    | '/categories'
    | '/help'
    | '/search'
    | '/stores'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/create-store'
    | '/account/addresses'
    | '/account/following'
    | '/account/orders'
    | '/account/payments'
    | '/account/reviews'
    | '/account/settings'
    | '/account/wishlist'
    | '/'
    | '/account/'
    | '/store/$storeSlug'
    | '/category/$categorySlug'
    | '/chat/$storeSlug'
    | '/product/$productSlug'
    | '/merchant/$storeId/analytics'
    | '/merchant/$storeId/messages'
    | '/merchant/$storeId/orders'
    | '/merchant/$storeId/payouts'
    | '/merchant/$storeId/product-new'
    | '/merchant/$storeId/products'
    | '/merchant/$storeId/promotions'
    | '/merchant/$storeId/reviews'
    | '/merchant/$storeId/settings'
    | '/chat/'
    | '/merchant/$storeId/'
    | '/store/$storeSlug/about'
    | '/store/$storeSlug/policies'
    | '/store/$storeSlug/reviews'
    | '/store/$storeSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/cart'
    | '/categories'
    | '/help'
    | '/search'
    | '/stores'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/create-store'
    | '/account/addresses'
    | '/account/following'
    | '/account/orders'
    | '/account/payments'
    | '/account/reviews'
    | '/account/settings'
    | '/account/wishlist'
    | '/'
    | '/account'
    | '/category/$categorySlug'
    | '/chat/$storeSlug'
    | '/product/$productSlug'
    | '/merchant/$storeId/analytics'
    | '/merchant/$storeId/messages'
    | '/merchant/$storeId/orders'
    | '/merchant/$storeId/payouts'
    | '/merchant/$storeId/product-new'
    | '/merchant/$storeId/products'
    | '/merchant/$storeId/promotions'
    | '/merchant/$storeId/reviews'
    | '/merchant/$storeId/settings'
    | '/chat'
    | '/merchant/$storeId'
    | '/store/$storeSlug/about'
    | '/store/$storeSlug/policies'
    | '/store/$storeSlug/reviews'
    | '/store/$storeSlug'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(forms)'
    | '/account'
    | '/deferred'
    | '/marketplace-guidelines'
    | '/privacy-policy'
    | '/store-terms-of-service'
    | '/terms-of-service'
    | '/(app)/chat'
    | '/merchant/$storeId'
    | '/(app)/cart'
    | '/(app)/categories'
    | '/(app)/help'
    | '/(app)/search'
    | '/(app)/stores'
    | '/(auth)/forgotpassword'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(forms)/create-store'
    | '/account/addresses'
    | '/account/following'
    | '/account/orders'
    | '/account/payments'
    | '/account/reviews'
    | '/account/settings'
    | '/account/wishlist'
    | '/(app)/'
    | '/account/'
    | '/(app)/store/$storeSlug'
    | '/(app)/category/$categorySlug'
    | '/(app)/chat/$storeSlug'
    | '/(app)/product/$productSlug'
    | '/merchant/$storeId/analytics'
    | '/merchant/$storeId/messages'
    | '/merchant/$storeId/orders'
    | '/merchant/$storeId/payouts'
    | '/merchant/$storeId/product-new'
    | '/merchant/$storeId/products'
    | '/merchant/$storeId/promotions'
    | '/merchant/$storeId/reviews'
    | '/merchant/$storeId/settings'
    | '/(app)/chat/'
    | '/merchant/$storeId/'
    | '/(app)/store/$storeSlug/about'
    | '/(app)/store/$storeSlug/policies'
    | '/(app)/store/$storeSlug/reviews'
    | '/(app)/store/$storeSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  formsRouteRoute: typeof formsRouteRouteWithChildren
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  MarketplaceGuidelinesRoute: typeof MarketplaceGuidelinesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StoreTermsOfServiceRoute: typeof StoreTermsOfServiceRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  MerchantStoreIdRouteRoute: typeof MerchantStoreIdRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-terms-of-service': {
      id: '/store-terms-of-service'
      path: '/store-terms-of-service'
      fullPath: '/store-terms-of-service'
      preLoaderRoute: typeof StoreTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-guidelines': {
      id: '/marketplace-guidelines'
      path: '/marketplace-guidelines'
      fullPath: '/marketplace-guidelines'
      preLoaderRoute: typeof MarketplaceGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(forms)': {
      id: '/(forms)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof formsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/following': {
      id: '/account/following'
      path: '/following'
      fullPath: '/account/following'
      preLoaderRoute: typeof AccountFollowingRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/(forms)/create-store': {
      id: '/(forms)/create-store'
      path: '/create-store'
      fullPath: '/create-store'
      preLoaderRoute: typeof formsCreateStoreRouteImport
      parentRoute: typeof formsRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgotpassword': {
      id: '/(auth)/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof authForgotpasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/stores': {
      id: '/(app)/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof appStoresRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/search': {
      id: '/(app)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof appSearchRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/help': {
      id: '/(app)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof appHelpRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/categories': {
      id: '/(app)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof appCategoriesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cart': {
      id: '/(app)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof appCartRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/merchant/$storeId': {
      id: '/merchant/$storeId'
      path: '/merchant/$storeId'
      fullPath: '/merchant/$storeId'
      preLoaderRoute: typeof MerchantStoreIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat': {
      id: '/(app)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/merchant/$storeId/': {
      id: '/merchant/$storeId/'
      path: '/'
      fullPath: '/merchant/$storeId/'
      preLoaderRoute: typeof MerchantStoreIdIndexRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appChatRouteRoute
    }
    '/merchant/$storeId/settings': {
      id: '/merchant/$storeId/settings'
      path: '/settings'
      fullPath: '/merchant/$storeId/settings'
      preLoaderRoute: typeof MerchantStoreIdSettingsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/reviews': {
      id: '/merchant/$storeId/reviews'
      path: '/reviews'
      fullPath: '/merchant/$storeId/reviews'
      preLoaderRoute: typeof MerchantStoreIdReviewsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/promotions': {
      id: '/merchant/$storeId/promotions'
      path: '/promotions'
      fullPath: '/merchant/$storeId/promotions'
      preLoaderRoute: typeof MerchantStoreIdPromotionsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/products': {
      id: '/merchant/$storeId/products'
      path: '/products'
      fullPath: '/merchant/$storeId/products'
      preLoaderRoute: typeof MerchantStoreIdProductsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/product-new': {
      id: '/merchant/$storeId/product-new'
      path: '/product-new'
      fullPath: '/merchant/$storeId/product-new'
      preLoaderRoute: typeof MerchantStoreIdProductNewRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/payouts': {
      id: '/merchant/$storeId/payouts'
      path: '/payouts'
      fullPath: '/merchant/$storeId/payouts'
      preLoaderRoute: typeof MerchantStoreIdPayoutsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/orders': {
      id: '/merchant/$storeId/orders'
      path: '/orders'
      fullPath: '/merchant/$storeId/orders'
      preLoaderRoute: typeof MerchantStoreIdOrdersRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/messages': {
      id: '/merchant/$storeId/messages'
      path: '/messages'
      fullPath: '/merchant/$storeId/messages'
      preLoaderRoute: typeof MerchantStoreIdMessagesRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/merchant/$storeId/analytics': {
      id: '/merchant/$storeId/analytics'
      path: '/analytics'
      fullPath: '/merchant/$storeId/analytics'
      preLoaderRoute: typeof MerchantStoreIdAnalyticsRouteImport
      parentRoute: typeof MerchantStoreIdRouteRoute
    }
    '/(app)/product/$productSlug': {
      id: '/(app)/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof appProductProductSlugRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/$storeSlug': {
      id: '/(app)/chat/$storeSlug'
      path: '/$storeSlug'
      fullPath: '/chat/$storeSlug'
      preLoaderRoute: typeof appChatStoreSlugRouteImport
      parentRoute: typeof appChatRouteRoute
    }
    '/(app)/category/$categorySlug': {
      id: '/(app)/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof appCategoryCategorySlugRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/store/$storeSlug': {
      id: '/(app)/store/$storeSlug'
      path: '/store/$storeSlug'
      fullPath: '/store/$storeSlug'
      preLoaderRoute: typeof appStoreStoreSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/store/$storeSlug/': {
      id: '/(app)/store/$storeSlug/'
      path: '/'
      fullPath: '/store/$storeSlug/'
      preLoaderRoute: typeof appStoreStoreSlugIndexRouteImport
      parentRoute: typeof appStoreStoreSlugRouteRoute
    }
    '/(app)/store/$storeSlug/reviews': {
      id: '/(app)/store/$storeSlug/reviews'
      path: '/reviews'
      fullPath: '/store/$storeSlug/reviews'
      preLoaderRoute: typeof appStoreStoreSlugReviewsRouteImport
      parentRoute: typeof appStoreStoreSlugRouteRoute
    }
    '/(app)/store/$storeSlug/policies': {
      id: '/(app)/store/$storeSlug/policies'
      path: '/policies'
      fullPath: '/store/$storeSlug/policies'
      preLoaderRoute: typeof appStoreStoreSlugPoliciesRouteImport
      parentRoute: typeof appStoreStoreSlugRouteRoute
    }
    '/(app)/store/$storeSlug/about': {
      id: '/(app)/store/$storeSlug/about'
      path: '/about'
      fullPath: '/store/$storeSlug/about'
      preLoaderRoute: typeof appStoreStoreSlugAboutRouteImport
      parentRoute: typeof appStoreStoreSlugRouteRoute
    }
  }
}

interface appChatRouteRouteChildren {
  appChatStoreSlugRoute: typeof appChatStoreSlugRoute
  appChatIndexRoute: typeof appChatIndexRoute
}

const appChatRouteRouteChildren: appChatRouteRouteChildren = {
  appChatStoreSlugRoute: appChatStoreSlugRoute,
  appChatIndexRoute: appChatIndexRoute,
}

const appChatRouteRouteWithChildren = appChatRouteRoute._addFileChildren(
  appChatRouteRouteChildren,
)

interface appStoreStoreSlugRouteRouteChildren {
  appStoreStoreSlugAboutRoute: typeof appStoreStoreSlugAboutRoute
  appStoreStoreSlugPoliciesRoute: typeof appStoreStoreSlugPoliciesRoute
  appStoreStoreSlugReviewsRoute: typeof appStoreStoreSlugReviewsRoute
  appStoreStoreSlugIndexRoute: typeof appStoreStoreSlugIndexRoute
}

const appStoreStoreSlugRouteRouteChildren: appStoreStoreSlugRouteRouteChildren =
  {
    appStoreStoreSlugAboutRoute: appStoreStoreSlugAboutRoute,
    appStoreStoreSlugPoliciesRoute: appStoreStoreSlugPoliciesRoute,
    appStoreStoreSlugReviewsRoute: appStoreStoreSlugReviewsRoute,
    appStoreStoreSlugIndexRoute: appStoreStoreSlugIndexRoute,
  }

const appStoreStoreSlugRouteRouteWithChildren =
  appStoreStoreSlugRouteRoute._addFileChildren(
    appStoreStoreSlugRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appChatRouteRoute: typeof appChatRouteRouteWithChildren
  appCartRoute: typeof appCartRoute
  appCategoriesRoute: typeof appCategoriesRoute
  appHelpRoute: typeof appHelpRoute
  appSearchRoute: typeof appSearchRoute
  appStoresRoute: typeof appStoresRoute
  appIndexRoute: typeof appIndexRoute
  appStoreStoreSlugRouteRoute: typeof appStoreStoreSlugRouteRouteWithChildren
  appCategoryCategorySlugRoute: typeof appCategoryCategorySlugRoute
  appProductProductSlugRoute: typeof appProductProductSlugRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChatRouteRoute: appChatRouteRouteWithChildren,
  appCartRoute: appCartRoute,
  appCategoriesRoute: appCategoriesRoute,
  appHelpRoute: appHelpRoute,
  appSearchRoute: appSearchRoute,
  appStoresRoute: appStoresRoute,
  appIndexRoute: appIndexRoute,
  appStoreStoreSlugRouteRoute: appStoreStoreSlugRouteRouteWithChildren,
  appCategoryCategorySlugRoute: appCategoryCategorySlugRoute,
  appProductProductSlugRoute: appProductProductSlugRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotpasswordRoute: typeof authForgotpasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotpasswordRoute: authForgotpasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface formsRouteRouteChildren {
  formsCreateStoreRoute: typeof formsCreateStoreRoute
}

const formsRouteRouteChildren: formsRouteRouteChildren = {
  formsCreateStoreRoute: formsCreateStoreRoute,
}

const formsRouteRouteWithChildren = formsRouteRoute._addFileChildren(
  formsRouteRouteChildren,
)

interface AccountRouteRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountFollowingRoute: typeof AccountFollowingRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountFollowingRoute: AccountFollowingRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface MerchantStoreIdRouteRouteChildren {
  MerchantStoreIdAnalyticsRoute: typeof MerchantStoreIdAnalyticsRoute
  MerchantStoreIdMessagesRoute: typeof MerchantStoreIdMessagesRoute
  MerchantStoreIdOrdersRoute: typeof MerchantStoreIdOrdersRoute
  MerchantStoreIdPayoutsRoute: typeof MerchantStoreIdPayoutsRoute
  MerchantStoreIdProductNewRoute: typeof MerchantStoreIdProductNewRoute
  MerchantStoreIdProductsRoute: typeof MerchantStoreIdProductsRoute
  MerchantStoreIdPromotionsRoute: typeof MerchantStoreIdPromotionsRoute
  MerchantStoreIdReviewsRoute: typeof MerchantStoreIdReviewsRoute
  MerchantStoreIdSettingsRoute: typeof MerchantStoreIdSettingsRoute
  MerchantStoreIdIndexRoute: typeof MerchantStoreIdIndexRoute
}

const MerchantStoreIdRouteRouteChildren: MerchantStoreIdRouteRouteChildren = {
  MerchantStoreIdAnalyticsRoute: MerchantStoreIdAnalyticsRoute,
  MerchantStoreIdMessagesRoute: MerchantStoreIdMessagesRoute,
  MerchantStoreIdOrdersRoute: MerchantStoreIdOrdersRoute,
  MerchantStoreIdPayoutsRoute: MerchantStoreIdPayoutsRoute,
  MerchantStoreIdProductNewRoute: MerchantStoreIdProductNewRoute,
  MerchantStoreIdProductsRoute: MerchantStoreIdProductsRoute,
  MerchantStoreIdPromotionsRoute: MerchantStoreIdPromotionsRoute,
  MerchantStoreIdReviewsRoute: MerchantStoreIdReviewsRoute,
  MerchantStoreIdSettingsRoute: MerchantStoreIdSettingsRoute,
  MerchantStoreIdIndexRoute: MerchantStoreIdIndexRoute,
}

const MerchantStoreIdRouteRouteWithChildren =
  MerchantStoreIdRouteRoute._addFileChildren(MerchantStoreIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  formsRouteRoute: formsRouteRouteWithChildren,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  DeferredRoute: DeferredRoute,
  MarketplaceGuidelinesRoute: MarketplaceGuidelinesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StoreTermsOfServiceRoute: StoreTermsOfServiceRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  MerchantStoreIdRouteRoute: MerchantStoreIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
